site:
  title: Bjornna  
  start_page: bjornna::index.adoc
git:
  ensure_git_suffix: false  
content:
  sources:  
  - url: https://github.com/bjornna/bjornna
    branches: main 
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://github.com/bjornna/antora-ui-bifrost/actions/runs/12439937868/artifacts/2350759350    
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll