antora:
  extensions:
  - '@antora/lunr-extension'
site:
  title: Bjornna  
  start_page: bjornna::index.adoc  
git:
  ensure_git_suffix: false  
content:
  sources:  
  - url: https://github.com/bjornna/bjornna
    branches: main 
  - url: https://github.com/ehrforce/onkodok
    branches: main 
  - url: https://dips@dev.azure.com/dips/DIPS%20Configured%20Products/_git/Personskade-Doc
    branches: antora
  - url: https://dips@dev.azure.com/dips/DIPS%20Configured%20Products/_git/DHACK-2024-MM
    branches: HEAD
    start_path: doc
  - url: https://dips@dev.azure.com/dips/DIPS%20Configured%20Products/_git/SurgeryQualityModule
    branches: master
    start_path: doc
  - url: https://dips@dev.azure.com/dips/DIPS%20Configured%20Products/_git/Oncology-Export
    branches: master
    start_path: doc    
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
    - asciidoctor-plantuml
ui:
  bundle:
    url: https://github.com/bjornna/antora-ui-bifrost/releases/download/v0.8.0/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
