antora:
  extensions:
  - '@antora/lunr-extension'
site:
  title: Bjornna  
  start_page: bjornna::index.adoc
git:
  ensure_git_suffix: false  
content:
  sources:  
  - url: https://github.com/bjornna/bjornna
    branches: main 
  - url: https://dips@dev.azure.com/dips/DIPS%20Configured%20Products/_git/Personskade-Doc
    branches: antora
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://github.com/bjornna/antora-ui-bifrost/releases/download/v0.5/ui-bundle.zip    
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
