site:
  title: Bjornna  
  start_page: bjornna::index.adoc
git:
  ensure_git_suffix: false  
content:
  sources:  
  - url: https://github.com/bjornna/bjornna
    branches: main 
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
